sonar.projectKey=ametowartem_book-service
sonar.organization=ametowartem
sonar.projectName=book-service
sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
sonar.language=ts
sonar.typescript.tsconfigPath=tsconfig.json
